### ISSUE TITLE
Cancel Coroutine Job

### ISSUE THREAD

**Issue by odaridavid** [Paulmburu/MoviesReview#4]
https://github.com/Paulmburu/MoviesReview/blob/a9b9a8ae388b883eeee40524a0da25dd18a7e95f/app/src/main/java/tk/paulmburu/moviesreview/MainActivity.kt#L23

Ideally, you could cancel the coroutine in the ```onDestory()``` method in the event the user, for example, closes the app or leaves the activity
To do that call
```kotlin
viewModeljob.cancel()
```
If you were using a viewModel with viewModelScope then it wouldn't be necessary to cancel.

**Comment by Paulmburu** [comment]
let me fix it out
